[build]
  command = ""
  publish = "."

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/ai"
  to = "/.netlify/functions/ai"
  status = 200

[[redirects]]
  from = "/beacon"
  to = "/.netlify/functions/beacon"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "DENY"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    # CSP enforced via <meta> tag in index.html to avoid double enforcement

[[headers]]
  for = "/icons/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/pwa/manifest.json"
    [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/pwa/service-worker.js"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/pwa/*"
    [headers.values]
    Cache-Control = "public, max-age=86400"
